### ISSUE TITLE
Failed to apply plugin [id 'nebula.lint']

### ISSUE THREAD

**Issue by RobertMlo** [nebula-plugins/gradle-lint-plugin#117]
I'm trying to apply a gradle lint to my spring project, but when I run a gradle, I receive the following exception due to `Failed to apply plugin [id 'nebula.lint']`:

```
Synchronize Gradle projects with workspace failed due to an error in the referenced Gradle build.
Could not run build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-3.4.1-all.zip'.

Build file 'path_to_file\build.gradle' line: 18
A problem occurred evaluating project ':projects:test'.
Failed to apply plugin [id 'nebula.lint']
Task with name 'fixGradleLint' not found in root project 'rootProject'.
org.gradle.tooling.BuildException: Could not run build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-3.4.1-all.zip'.
	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:51)
	//...
Caused by: org.gradle.internal.exceptions.LocationAwareException: Build file 'path_to_file\build.gradle' line: 18
A problem occurred evaluating project ':projects:test'.
	at org.gradle.initialization.DefaultExceptionAnalyser.transform(DefaultExceptionAnalyser.java:74)
	//...
Caused by: org.gradle.api.GradleScriptException: A problem occurred evaluating project ':projects:test'.
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:92)
	//...
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [id 'nebula.lint']
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:155)
	//...
Caused by: org.gradle.api.UnknownTaskException: Task with name 'fixGradleLint' not found in root project 'rootProject'.
	at org.gradle.api.internal.tasks.DefaultTaskCollection.createNotFoundException(DefaultTaskCollection.java:80)
	//...
```

Here is my `build.gradle` file:

```gradle
def artifact = 'client'

buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "gradle.plugin.org.akhikhl.gretty:gretty:1.4.2"
    classpath "com.netflix.nebula:gradle-lint-plugin:7.3.5"
  }
}

apply plugin: 'java'
apply plugin: 'war'
apply plugin: 'org.akhikhl.gretty'
apply plugin: 'nebula.lint'

war {
	baseName = 'test'
}

sourceCompatibility = 1.8

repositories {
	mavenLocal()
	mavenCentral()
}

configurations {
	providedRuntime
}

gradleLint.rules = ['unused-dependency']

gretty {
	httpPort = 8090
	httpsEnabled = true
	httpsPort = 8443
	contextPath = '/test'
}

dependencies {
	compile('org.springframework:spring-core:4.3.6.RELEASE')
	compile('org.springframework:spring-web:4.3.6.RELEASE')
	compile('javax.servlet:javax.servlet-api:3.1.0')
	compile('io.swagger:' + artifact + ':1.0.0')
	compile project(':projects:SDK')
        // other
}
```

**Comment by cyrusbuilt** [comment]
Is there still no solution for this?

**Comment by chali** [comment]
Hi @cyrusbuilt, personally I haven't seen this issue before but all versions involved in the example above are quite old. Could you try your project with latest Gradle 4.6 and latest nebula.lint version 9.3.1? If your problems will still be present could you provide your build file?

**Comment by ekans** [comment]
I had the same problem if I apply the plugin on a sub-project.
It seems the plugin must be apply on the root project.

**Comment by tehbilly** [comment]
I've gotten around this by including the plugin in the root project, applying it to subprojects, and then running `:sub-project:fixGradleLint`. Definitely confusing what's wrong when trying to apply it to a subproject only.

**Comment by getalphacode** [comment]
Facing the exact same issue!

**Comment by neilabdev** [comment]
+1

**Comment by adamwojszczyk** [comment]
+1

**Comment by jayudhandha** [comment]
+1

**Comment by chali** [comment]
@nickcotter @tehbilly @getalphacode @neilabdev I think your issue might be slightly different. The original description is about missing `fixGradleLint` task in the root project. I'm assuming from your comments that call the task in a submodule. The task is actually available only in the root so the error would be expected. The only way how to run it is `./gradlew fixGradleLint` for the whole project.

**Comment by helton-isac** [comment]
I had the same issue with the 6.1.4 and 9.3.2. But using the latest one 16.9.1 the error doesn`t happen anymore

**Comment by chali** [comment]
I'm going to close the issue since the situation seems to be not relevant anymore.

**Comment by anentropic** [comment]
I'm new to Gradle...

I started a new project according to https://docs.gradle.org/current/samples/sample_building_java_applications.html#run_the_init_task

Then I wanted to lint for unused dependencies, since I suspect I added some I don't strictly need, and I found this article which led me to `nebula.lint`:
https://www.baeldung.com/gradle-finding-unused-dependencies

I have an `app/build.gradle` file like:
```groovy
plugins {
    id 'application'
    id "nebula.lint" version "16.23.0"
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'junit:junit:4.13.1'

    implementation 'com.google.guava:guava:30.0-jre' // specified by gradle init
    ...
    blah blah
    ...
}

allprojects {
    buildscript {
        repositories { mavenCentral() }
        dependencies {
            classpath 'com.netflix.nebula:gradle-lint-plugin:latest.release'
        }
    }
    apply plugin: "nebula.lint"
    gradleLint {
        rules=['unused-dependency']
    }
}

application {
    mainClass = 'myapp.App'
}
```
when I try to lint:
```
$ ./gradlew lintGradle

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/anentropic/Dev/myapp/app/build.gradle' line: 3

* What went wrong:
An exception occurred applying plugin request [id: 'application']
> Failed to apply plugin class 'org.gradle.api.plugins.JavaBasePlugin'.
   > Task with name 'fixGradleLint' not found in root project 'myapp'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 695ms
```

Can you please point me in the right direction...

I feel like probably the config examples in the readme of this repo are just snippets that people experienced with Gradle know what to do with and maybe I've copy and pasted them in the wrong place somehow

I've tried it a few different ways and the ones that aren't totally invalid all fail with the error above.

**Comment by chali** [comment]
@anentropic The lint plugin should be applied only in the root project. So you can do the plugin block application in the root. And then:
```
gradleLint {
        rules=['unused-dependency']
    }
```

I don't think you need the `allprojects` part.
