### ISSUE TITLE
Non-resolvable configurations impact correctness of dependency rules

### ISSUE THREAD

**Issue by DanielThomas** [nebula-plugins/gradle-lint-plugin#126]
Many configurations are no longer directly resolvable, such as `compileOnly` or `implementation`, which means we've had to add exclusions on non-resolvable configurations. That means we can't lint them effectively, so we'll need to add logic that knows how to handle these, by looking at configurations that extends them, etc.

**Comment by elivings** [comment]
Any update on this?

**Comment by rpalcolea** [comment]
v15.0.0 should have better support for this: https://github.com/nebula-plugins/gradle-lint-plugin/releases/tag/v15.0.0
