### ISSUE TITLE
7.5.0 is not on Maven Central or jcenter

### ISSUE THREAD

**Issue by pcarrier** [nebula-plugins/gradle-lint-plugin#127]
@DanielThomas any idea why? This is quite impactful for us as we're already on Gradle 4.0.

**Comment by DanielThomas** [comment]
Oops, I hadn't noticed something was up with Circle CI. Let me look into that.

**Comment by DanielThomas** [comment]
Ah, think these happened on a day of a Bintray outage. I'll get a v7.8.0 out for you.

**Comment by DanielThomas** [comment]
7.8.0 is on Bintray and JCenter, and will sync to Maven Central shortly.
