### ISSUE TITLE
compatibilty with gradle 4

### ISSUE THREAD

**Issue by abnud1** [nebula-plugins/gradle-lint-plugin#136]
I added the `all-dependency` rule and tried to lint the project but it failed with this error :  

> Execution failed for task ':lintGradle'.
> > No signature of method: org.gradle.api.internal.artifacts.ivyservice.ivyresolve.strategy.DefaultVersionComparator.asStringComparator() is applicable for argument types: () values: []
>   Possible solutions: asVersionComparator()

the stacktrace is :  

> 

> * Exception is:
> org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':lintGradle'.
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
>         at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
>         at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
>         at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
>         at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
>         at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
>         at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
>         at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
>         at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
>         at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
>         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:242)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
>         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:235)
>         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:224)
>         at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:121)
>         at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:77)
>         at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:102)
>         at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:96)
>         at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:612)
>         at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:567)
>         at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:96)
>         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
>         at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
>         at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
> Caused by: groovy.lang.MissingMethodException: No signature of method: org.gradle.api.internal.artifacts.ivyservice.ivyresolve.strategy.DefaultVersionComparator.asStringComparator() is applicable for argument types: () values: []
> Possible solutions: asVersionComparator()
>         at com.netflix.nebula.lint.rule.dependency.DependencyService.<init>(DependencyService.groovy:44)
>         at com.netflix.nebula.lint.rule.dependency.DependencyService.forProject(DependencyService.groovy:31)
>         at com.netflix.nebula.lint.rule.dependency.DependencyService$forProject.call(Unknown Source)
>         at com.netflix.nebula.lint.rule.dependency.UnusedDependencyRule.beforeApplyTo(UnusedDependencyRule.groovy:24)
>         at com.netflix.nebula.lint.rule.GradleLintRule.applyTo(GradleLintRule.groovy:157)
>         at com.netflix.nebula.lint.org.codenarc.rule.Rule$applyTo$0.call(Unknown Source)
>         at com.netflix.nebula.lint.org.codenarc.rule.Rule$applyTo$0.call(Unknown Source)
>         at com.netflix.nebula.lint.org.codenarc.analyzer.AbstractSourceAnalyzer.collectViolations(AbstractSourceAnalyzer.groovy:40)
>         at com.netflix.nebula.lint.plugin.LintService$ReportableAnalyzer.analyze(LintService.groovy:55)
>         at com.netflix.nebula.lint.plugin.LintService$ReportableAnalyzer$analyze.call(Unknown Source)
>         at com.netflix.nebula.lint.plugin.LintService$_lint_closure4.doCall(LintService.groovy:122)
>         at com.netflix.nebula.lint.plugin.LintService.lint(LintService.groovy:112)
>         at com.netflix.nebula.lint.plugin.LintService$lint.call(Unknown Source)
>         at com.netflix.nebula.lint.plugin.LintGradleTask.lint(LintGradleTask.groovy:34)
>         at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
>         at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
>         at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
>         at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
>         at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:711)
>         at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:694)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
>         ... 27 more
> 
I had another plugin which had an error similar to this and the error disappeared upon updating the plugin so I'm thinking that the problem is compatibility with gradle 4 .

**Comment by DanielThomas** [comment]
That's right, was fixed in 7.5.0 (I also made that change in the core that caused the compatibility issue - so we got ahead of it).

**Comment by aliceyoung44** [comment]
And where exactly is 7.5.0? 7.4.0 is the current version, even 3+ months after this post.

**Comment by DanielThomas** [comment]
@aliceyoung44 not sure what you mean?

https://github.com/nebula-plugins/gradle-lint-plugin/releases
https://plugins.gradle.org/plugin/nebula.lint

**Comment by tkruse** [comment]
maven central does not list versions between 7.4 and 7.8
https://mvnrepository.com/artifact/com.netflix.nebula/gradle-lint-plugin

Also, I have the same problem, but seems to be inside gradle-info-plugin:
```
 Failed to apply plugin [class 'nebula.plugin.info.dependencies.DependenciesInfoPlugin']
   > Could not create plugin of type 'DependenciesInfoPlugin'.
      > No signature of method: org.gradle.api.internal.artifacts.ivyservice.ivyresolve.strategy.DefaultVersionComparator.asStringComparator() is applicable for argument types: () values: []
```

gradle-lint-plugin 8.3.1 still seems to use gradle-info-plugin 3.3.5  instead of latest 3.6.0. 
(https://mvnrepository.com/artifact/com.netflix.nebula/gradle-lint-plugin/8.3.1)

Solved for me by using both:
```
plugins {
    id 'nebula.lint' version '8.3.1'
    id 'nebula.info' version '3.6.0'
}
```

**Comment by adrian-baker** [comment]
Perhaps worth updating the doc at https://github.com/nebula-plugins/gradle-lint-plugin, like clockwork I added the dependency line in, got this error, googled, ended up here, realised I had imported an old version.

**Comment by shubh10** [comment]
@DanielThomas he meant the version in readme  & the documentation shows version '7.4.0' as the latest. It is very misleading, unless someone decides to visit 'releases' page.
