### ISSUE TITLE
Task has not declared any outputs?

### ISSUE THREAD

**Issue by philbert** [nebula-plugins/gradle-lint-plugin#16]
I've found some curious code in a project that I am trying to modify, so I figured that the gradle lint plugin might help me figure out if there was a problem or not.

Curiously, when I run lintGradle though, there is no output. I cannot believe this is perfect code, so I assume there is something I am doing wrong. Can you point me in the right direction?

```
11:24:31.988 [INFO] [org.gradle.BuildLogger] Tasks to be executed: [task ':lintGradle']
11:24:32.005 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :lintGradle (Thread[main,5,main]) started.
11:24:32.006 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :lintGradle
11:24:32.007 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':lintGradle'
11:24:32.008 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Determining if task ':lintGradle' is up-to-date
11:24:32.009 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Executing task ':lintGradle' (up-to-date check took 0.001 secs) due to:
  Task has not declared any outputs.
11:24:32.010 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':lintGradle'.
11:24:32.076 [INFO] [org.codenarc.ruleregistry.PropertiesFileRuleRegistry] Loaded properties file in 16ms; 348 rules
11:24:32.143 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':lintGradle'
11:24:32.144 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :lintGradle (Thread[main,5,main]) completed. Took 0.138 secs.
11:24:32.145 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 0.138 secs, idle: 0.002 secs
11:24:32.146 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskGraphExecuter] Timing: Executing the DAG took 0.159 secs
11:24:32.146 [LIFECYCLE] [org.gradle.BuildResultLogger]
11:24:32.148 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD SUCCESSFUL
11:24:32.149 [LIFECYCLE] [org.gradle.BuildResultLogger]
11:24:32.149 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 5.691 secs
```

**Comment by DanielThomas** [comment]
If there are no lint violations, that's what you'll see. Did you have a lint rule enabled that you expected to trigger for this project?

**Comment by philbert** [comment]
This is my first real experience with groovy so I'm learning as I go. My specific issue is with [this file](https://github.com/ghale/gradle-jenkins-plugin/blob/master/src/main/groovy/com/terrafolio/gradle/plugins/jenkins/jobdsl/MapJobManagement.groovy)

There are two declarations of the overriding method called ```createOrUpdateConfig``` which appear could have been produced by a merge error. 

That looks really weird to me but the compilation succeeds, so I was hoping that linting might give me some idea whether this is an error or not. 

I hope that lint is not working correctly... otherwise if that is a valid declaration in groovy... then I don't know what to say really... 😕

**Comment by philbert** [comment]
Yeah looks like the lint is not working because ```gradle build``` breaks during compilation but ```gradle lintGradle``` still succeeds with no warnings.

Here is the first part of my build.gradle file. Is there something obviously wrong here?

```
buildscript {
    repositories {
        jcenter()
        maven {
            url 'http://repo.jenkins-ci.org/releases/'
        }
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }

    dependencies {
        classpath 'org.gradle.api.plugins:gradle-nexus-plugin:0.7'
        classpath "com.gradle.publish:plugin-publish-plugin:0.9.3"
        classpath 'com.netflix.nebula:gradle-lint-plugin:latest.release'
    }
}

apply plugin: "com.gradle.plugin-publish"
apply plugin: 'groovy'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'nexus'
apply plugin: 'nebula.lint'
```

**Comment by philbert** [comment]
One of the java developers here allayed my concerns [here](https://github.com/nebula-plugins/gradle-lint-plugin/issues/16#issuecomment-217121217) saying that pattern was totally cool and normal, so ok, sure...

But then maybe you can provide me a code snippet that should produce a lint error so I can confirm that lint is actually working correctly in my project so I can close this issue?

**Comment by jkschneider** [comment]
@philbert Sorry for the confusion. This plugin looks for violations of rules that you declare specifically. A [working example](https://github.com/nebula-plugins/gradle-lint-plugin/tree/master/example), though a triviality compared to what we actually do with it generally, is included with the plugin itself.
