### ISSUE TITLE
GenerateGradleLintReport fails

### ISSUE THREAD

**Issue by CSBaum** [nebula-plugins/gradle-lint-plugin#17]
I just saw the report task and thought i would give it a shot hoping that it is something i can use to justify the corp wide adoption of the plugin, but when ran it I got this:

```
:generateGradleLintReport FAILED
:lintGradle

This project contains lint violations. A complete listing of the violations follows. 
Because none were serious, the build's overall status was unaffected.

.
.
.

warning   unused-dependency                  this dependency is unused and can be removed
build.gradle:189
compile ('org.ini4j:ini4j:0.5.4') {transitive = false}

✖ build.gradle: 19 problems (0 errors, 19 warnings)

To apply fixes automatically, run fixGradleLint, review, and commit the changes.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateGradleLintReport'.
> Not supported on virtual results
```

**Comment by DanielThomas** [comment]
Thanks for the report @CSBaum. Would you mind running with `-s` so we have the stacktrace for the failure?

**Comment by CSBaum** [comment]
Sorry, i should have realized that would be the 1st thing asked for ... it's attached now :)
[gGLR_stacktrace.txt](https://github.com/nebula-plugins/gradle-lint-plugin/files/249478/gGLR_stacktrace.txt)
