### ISSUE TITLE
unused implementation not recognized

### ISSUE THREAD

**Issue by Goran1708** [nebula-plugins/gradle-lint-plugin#186]
unused dependency will be reported if I use this format   `compile 'com.airbnb.android:lottie:2.5.5'` but if I use this format `implementation 'com.airbnb.android:lottie:2.5.5'` it will not tell me I have unused dependency.

**Comment by martiwi** [comment]
I have the same issue, not lint issues when I add extra un-used dependencies with the `implementation` key form `dependencies {}`

**Comment by chali** [comment]
Unfortunately, we don't support configurations such us `implementation` and `api` in this plugin at this point and we even don't have a plan to add them in the near future.

**Comment by chali** [comment]
It is related to #203 and #205 so I closed this thread.
