### ISSUE TITLE
GradleDependency can't parse dependency without version

### ISSUE THREAD

**Issue by dansanduleac** [nebula-plugins/gradle-lint-plugin#199]
While GradleDependency can parse dependency notatations without versions like
```
org.immutables:value
```

It won't parse ones that have a classifier / extension, like so:
```
org.immutables:value::annotations
```

This is because the regex forces the version to be non-empty if the further components are set:
https://github.com/nebula-plugins/gradle-lint-plugin/blob/d9885620c96d0c1574099f82c018c2a61fd03479/src/main/groovy/com/netflix/nebula/lint/rule/GradleDependency.groovy#L74

**Comment by rpalcolea** [comment]
Hi @dansanduleac,
This is fixed in v10.1.3
