### ISSUE TITLE
Deprecated 'compile' for 'implementation' or 'api'

### ISSUE THREAD

**Issue by phreed** [nebula-plugins/gradle-lint-plugin#203]
Several dependencies configurations have been deprecated but gradle-lint-plugin makes recommendations to use those deprecated keywords:
- https://docs.gradle.org/current/userguide/java_plugin.html
- https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation

e.g. testCompile, compile, runtime have all been deprecated.

**Comment by rpalcolea** [comment]
Hi @phreed ,

Thanks for the report. 

Any chance you would like to open a pull request for this?

**Comment by phreed** [comment]
I am still learning gradle generally.
I will take a look but it is probably beyond my current abilities.

**Comment by rpalcolea** [comment]
Hi @phreed ,

v10.2.0 contains a rule to replace deprecated dependency configurations.

compile -> implementation
testCompile -> testImplementation
runtime -> runtimeOnly

This can be applied via deprecated-dependency-configuration rule. Ex. `gradleLint.rules = ['deprecated-dependency-configuration']`

While there is some interest of doing this in all our existing rules, this requires a bigger work and also it wouldn't be backwards compatible. 

Unfortunately, these configurations were not introduced on a Gradle major version and we still support projects with gradle 4.0 <-> 4.6 which are not aware of `implementation` and so on.

Please let us know if this helps in the mean time

**Comment by phreed** [comment]
I presume the usage would be...
```
gradleLint {
      rules = ['deprecated-dependency-configuration']  // not including ['all-dependency']
      criticalRules = []
}
```
This seems to give the result I expect.
In particular, in my case, it recommends replacing `runtime` with `runtimeOnly`.

If I include the `all-dependency` rule I get many warning of the form...

```
warning   unused-dependency  this dependency should be moved to configuration **compile**
DAConformanceTest/edu.vanderbilt.isis.face.v30.architecturemodel.validation.ocl/build.gradle:25
implementation transitive: false, group: 'org.eclipse.ocl.examples', name: 'org.eclipse.ocl.examples.xtext.completeocl', version: '3.3.0.v20130523-1559'
```

Which seems to indicate replacing `implementation` with `compile`.

```
warning   unused-dependency   one or more classes in junit:junit:4.12 are required by your code directly
```

and

```
warning   undeclared-dependency    one or more classes in org.eclipse.emf:org.eclipse.emf.ecore:2.9.2-v20131212-0545 are required by your code directly
```
These two give different warnings but the explanation is the same.
What does the directive mean?

**Comment by trejkaz** [comment]
We see a similar thing to what's mentioned in that last comment, except that both warnings reference the same dependency.

    warning   unused-dependency                  one or more classes in org.hamcrest:hamcrest-core:1.3 are required by your code directly
    
    warning   undeclared-dependency              one or more classes in org.hamcrest:hamcrest-core:1.3 are required by your code directly

I thought the two were supposed to differ, though.

1. `undeclared-dependency` is supposed to be the warning for a dependency which is being used, but not declared.
2. `unused-dependency` is supposed to be the warning for a dependency which is being declared, but not used.

In this particular case, it's saying that the dependency is being referenced by the code, so surely only `undeclared-dependency` is correct, and the other is a bug in the plugin.

**Comment by rpalcolea** [comment]
Hi folks, this is also related to https://github.com/nebula-plugins/gradle-lint-plugin/issues/205 

This is a big change in the plugin since `implementation` behaves different. While we would love to do this right now, we don't have enough resources for the next few weeks. 

We will try to pick this up as soon as possible

**Comment by maguro** [comment]
Just curious, is this in the pipeline at all?

**Comment by chali** [comment]
Hi @maguro unfortunately, there is currently no plan to extend lint to support those configurations.

**Comment by maguro** [comment]
Would you accept a PR?

**Comment by chali** [comment]
@maguro sure, if you are interested in working on that feature.

**Comment by maguro** [comment]
Ok, not sure how soon it will get done.  Please ping me should anyone want to pick it up.

**Comment by kibbled** [comment]
There should be a huge warning on the README.me that warns developers not to use this plugin if they are using api or implementation.

**Comment by rpalcolea** [comment]
v15.0.0 should have better support for this: https://github.com/nebula-plugins/gradle-lint-plugin/releases/tag/v15.0.0

**Comment by proppy** [comment]
It seems that `v15.0.1` regressed on this, ` undeclared-dependency` and `unused-dependency` warnings that went away in `v15.0.0` when using `implementation` started appearing again w/ `v15.0.1+`
