### ISSUE TITLE
undeclared-dependency check not aware of api/implementation declared dependencies

### ISSUE THREAD

**Issue by clenart** [nebula-plugins/gradle-lint-plugin#205]
In my project, I am using api/implementation to declare my gradle dependencies.

If I add the undeclared-dependency check, the plugin complains that all of my dependencies are not declared. The fix action will add the dependencies a second time, with the compile prefix this time.

Seems like the plugin is just not aware of api/implementation declared dependencies.

**Comment by clenart** [comment]
This is with version 10.2.0 of the plugin.

**Comment by rpalcolea** [comment]
v15.0.0 should have better support for this: https://github.com/nebula-plugins/gradle-lint-plugin/releases/tag/v15.0.0

**Comment by boris-petrov** [comment]
@rpalcolea - this still doesn't work right when used with custom source sets. I have a `backend` sourceset and have many dependencies like `backendImplementation` and Gradle Lint doesn't seem to use those and gives a lot of `unused-dependency` and `undeclared-dependency` warnings. Is that normal or am I doing something wrong? And should I open a new issue about this?
