### ISSUE TITLE
Feature request: Warn on missing test functionality

### ISSUE THREAD

**Issue by mcandre** [nebula-plugins/gradle-lint-plugin#222]
* Warn on empty unit test suite
* Warn on missing code coverage (e.g. JaCoCo, Cobertura)

**Comment by chali** [comment]
Hi @mcandre this is certainly a good feature to have. Unfortunately, I don't think lint is a good place for it. Its main purpose is to help with build related things. I would point you to tools like https://www.sonarqube.org/ which are aiming in the direction you want to.
