### ISSUE TITLE
All Dependency Rule's documentation is incorrect

### ISSUE THREAD

**Issue by jsotuyod** [nebula-plugins/gradle-lint-plugin#24]
[The doc for the rule](https://github.com/nebula-plugins/gradle-lint-plugin/wiki/All-Dependency-Rule) states that to enable it one should use

```
gradleLint.rules += 'overridden-dependency-version'
```

But that is the name of the [Overriden Dependency Version Rule](https://github.com/nebula-plugins/gradle-lint-plugin/wiki/Overridden-Dependency-Version-Rule), and is clearly a copy & paste

**Comment by jkschneider** [comment]
Thanks again!
