### ISSUE TITLE
[16.2.1] Cannot suppress transitive-duplicate-dependency-class

### ISSUE THREAD

**Issue by boris-petrov** [nebula-plugins/gradle-lint-plugin#287]
```gradle
plugins {
	id 'java'
	id 'nebula.lint' version '16.2.1'
}

repositories {
	mavenCentral()
}

gradleLint {
	criticalRules = ['transitive-duplicate-dependency-class']
}

dependencies {
	gradleLint.ignore('transitive-duplicate-dependency-class') {
		implementation 'nu.validator:validator:18.11.5'
	}
	runtimeOnly 'org.subethamail:subethasmtp:3.1.7'
}
```

Run `gradle autoLintGradle` on this. You'll get:

```
error     transitive-duplicate-dependency-classnu.validator:cssvalidator:1.0.4 in configuration ':runtimeOnly' has 2 classes duplicated by org.w3c.jigsaw:jigsaw:2.2.6 (use --info for detailed class list) (no auto-fix available)
```

Which doesn't make sense as that error is ignored for the `nu.validator` line.

Removing the `runtimeOnly` line or moving it inside the `gradleLint.ignore` block fixes the issue.

**Comment by boris-petrov** [comment]
An even simpler example is `org.apache.tika:tika-parsers-standard-package:2.0.0`. Adding that as a `runtimeOnly` dependency leads to a `transitive-duplicate-dependency-class` warning which cannot be suppressed in any way.

**Comment by chali** [comment]
This is very likely a quirk of the way how we discover those dependencies. Most rules are walking AST for the build file and if we encounter an ignore block the walk is not continuing that branch. However, dependencies are discovered by resolving from the `Project` model. I'm worried that it might be too hard to track back that the dependency is actually wrapped in the ignore block. I will check it out.

**Comment by chali** [comment]
Yes, sadly this is not easily solvable :-( the `nu.validator:cssvalidator:1.0.4` dependency is transitivie dependency of `nu.validator:validator:18.11.5` but that ignore will only work if the declared dependency has duplicate classes. We don't have connection to original declared dependencies so we could check if they were wrapped in ignore. I found this a bit strange workaround:

```
plugins {
	id 'java'
	id 'nebula.lint' version '16.2.1'
}

repositories {
	mavenCentral()
}

gradleLint {
	criticalRules = ['transitive-duplicate-dependency-class']
}

configurations {
    ignoreCheck
}

dependencies {
	gradleLint.ignore('transitive-duplicate-dependency-class') {
             ignoreCheck 'nu.validator:cssvalidator:1.0.4'
	}
        mplementation 'nu.validator:validator:18.11.5'
	runtimeOnly 'org.subethamail:subethasmtp:3.1.7'
}
```
I declared the problematic dependency directly to a configuration that is not used at all but the fact that it is wrapped in ignore is configuring the rule to ignore this specific source of linting error.

Hopefully that at least help a bit.

**Comment by boris-petrov** [comment]
@chali - thanks! What you suggest works. However, the only "bad" thing about this is that I cannot seem to be able to use interpolation for the version. This works:

```gradle
	gradleLint.ignore('transitive-duplicate-dependency-class') {
		ignoreCheck 'nu.validator:cssvalidator:1.0.4'
	}
```

Neither of those two work:

```gradle
	gradleLint.ignore('transitive-duplicate-dependency-class') {
		ignoreCheck 'nu.validator:cssvalidator:+'
	}
```

```gradle
def cssValidatorVersion = '1.0.4'
...
	gradleLint.ignore('transitive-duplicate-dependency-class') {
		ignoreCheck "nu.validator:cssvalidator:$cssValidatorVersion"
	}
```

Perhaps that is related to #224. Any ideas if I/you can make any of the two work? I would really like this because right now I have duplicated my dependency versions because of this...

**Comment by chali** [comment]
This is unfortunately again related to the nature of the underlying AST we get for the build script. We collect exactly what is in the build file and then it is compared against the final resolved version. So for the second case, there is no dynamic version range matching it is simple as `'+' == '1.0.4'`, and that is false. Similarly the 3rd case, AST will not give us the final interpolated string but variable. 

I can see that this is far from the ideal since the final resolved version can easily change so the ignore became useless. I will look if there is some way to improve it. But I cannot make any promises.
