### ISSUE TITLE
lintGradle fails when using api dependencies on gradle feature variants

### ISSUE THREAD

**Issue by marklundberg** [nebula-plugins/gradle-lint-plugin#328]
// DependencyService.findAndReplaceNonResolvableConfiguration() does not support the Api configurations
// that are automatically added by gradle feature variants such as testFixtures and custom created features.

plugins {
    id 'java-library'
    id 'java-test-fixtures'
    id 'nebula.lint'
}

gradleLint {
    rules = ['all-dependency']
    autoLintAfterFailure = false
    alwaysRun = false
}

repositories {
    mavenCentral()
}

sourceSets {
    jdk8 {
        java {
            srcDirs = sourceSets.main.java.srcDirs
        }
    }
}

java {
    registerFeature('jdk8') {
        usingSourceSet(sourceSets.jdk8)
    }
}

dependencies {
    // lintGradle fails because testFixturesApi is not resolvable and is not replaced with testFixturesCompileClasspath.
    testFixturesApi 'org.hamcrest:hamcrest-core:1.3'
}

dependencies {
    // lintGradle fails because jdk8Api is not resolvable and is not replaced with jdk8CompileClasspath.
    jdk8Api 'com.google.code.findbugs:jsr305:3.0.2'
}

**Comment by StevenGerdes** [comment]
Just in case it isn't obvious to people finding this issue, a workaround for a multi project build in which only a few subprojects use testFixturesApi configuration is to just skip that subproject ` ./gradlew generateGradleLintReport -x :my-sub-project:generateGradleLintReport` I have a hunch this might cause some false positives, but overall it works for me to remove many duplicate dependencies.

**Comment by chali** [comment]
Hello folks, we have released version `17.0.0` and I think this situation should be fixed there.
