### ISSUE TITLE
compileConfigurationName no longer supported in Gradle 7

### ISSUE THREAD

**Issue by maguro** [nebula-plugins/gradle-lint-plugin#337]
`compileConfigurationName` was deprecated in Gradle 6. Now it is gone. I think it should be replaced by `compileClasspathConfigurationName`.

I get the following error:
```
* What went wrong:
Execution failed for task ':lintGradle'.
> Could not get unknown property 'compileConfigurationName' for source set 'main' of type org.gradle.api.internal.tasks.DefaultSourceSet.
```

**Comment by chali** [comment]
Hi @maguro thank you for the report. I'm working on Gradle 7 migration and this error is only a tip of the iceberk. We have released a candidate version with many fixes this one included. I have described details about how to consume such a version in this PR #335
