### ISSUE TITLE
 Plugin should not use the deprecated GUtil.loadProperties() function

### ISSUE THREAD

**Issue by eskatos** [nebula-plugins/gradle-lint-plugin#378]
In Gradle 7.1, `org.gradle.util.GUtil` has been soft deprecated (`@Deprecated` annotation).

For Gradle 7.6 we wanted to add deprecation nagging to it. Our smoke tests show that the Nebula Lint Plugin still uses the `GUtil.loadProperties()` function. We will postpone adding the deprecation nagging because users currently cannot resolve it.

Could you please look into removing that usage from the Nebula Lint Plugin?

**Comment by eskatos** [comment]
FYI we plan to start nagging in Gradle 8.1

**Comment by rpalcolea** [comment]
Hi, sorry for the super late response.

This is not used anymore 👍 since 18.0.x
