### ISSUE TITLE
[18.0.0] `java.lang.ClassNotFoundException: com.netflix.nebula.interop.GradleKt`

### ISSUE THREAD

**Issue by boris-petrov** [nebula-plugins/gradle-lint-plugin#383]
Upgrading to 18.0.0 from 17.8.0 causes any task I try to execute to lead to `java.lang.ClassNotFoundException: com.netflix.nebula.interop.GradleKt`. Gradle 7.6.

**Comment by patelharigopal** [comment]
We used this plugin in gradle and yesterday our all components Build is failed, root cases is upgraded nebula.lint 17.8.0 to 18.0.0.

- Gradle version : 7.4.2

> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file '/home/***/build.gradle' line: ***
> 
> * What went wrong:
> A problem occurred evaluating root project '***'.
> > com/netflix/nebula/interop/GradleKt
> 
> 
> Caused by: java.lang.NoClassDefFoundError: com/netflix/nebula/interop/GradleKt
>         at com.netflix.nebula.lint.plugin.GradleLintPlugin.apply(GradleLintPlugin.groovy:36)
>         at com.netflix.nebula.lint.plugin.GradleLintPlugin.apply(GradleLintPlugin.groovy)
>         at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:43)
>         at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:51)
>         at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:187)
>         at org.gradle.api.internal.plugins.DefaultPluginManager.access$100(DefaultPluginManager.java:52)
>         at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:282)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
>         at org.gradle.api.internal.plugins.DefaultPluginManager.lambda$doApply$0(DefaultPluginManager.java:167)
>         at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:44)
>         at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:166)
>         at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:146)
>         at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:167)
>         at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:43)
>         at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:98)
>         at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:190)
>         at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:49)
>         at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.java:37)
>         at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
>         at ***.run(***\build.gradle:49)

Can you shagged me solution for this error?

**Comment by Grimoren** [comment]
From the comparison : https://github.com/nebula-plugins/gradle-lint-plugin/compare/v17.8.0...v18.0.0
It looks like the gradle wrapper was changed to 8.0-rc2.

As far as I know, gradle plugins are incompatible with gradle versions prior to their version. So my guess is gradle 18.0.0 is not compatible with gradle 7-

**Comment by sethdarragile6** [comment]
We're getting the same exception with 18.0.0, also related to the gradle wrapper as mentioned above. We're using gradle 7.5.

**Comment by nikosmoum** [comment]
Same issue: upgrading from 17.8.0 to 18.0.0, using Gradle 7.6, breaks gradle

**Comment by boris-petrov** [comment]
I believe this issue has been fixed with version 18.0.1. Thanks!
