### ISSUE TITLE
README says lintGradle is the task. It's not. It is gradleLint

### ISSUE THREAD

**Issue by mmoayyed** [nebula-plugins/gradle-lint-plugin#4]
See:

```
Other tasks
-----------
allDepInsight
allDeps
cleanIdeaWorkspace
cleanLogs - Clean build log files
dependencyManagement
findbugs
findbugsTest - Run FindBugs analysis for test classes
fixGradleLint
generateGradleLintReport
gradleLint
install - Installs the 'archives' artifacts into the local Maven repository.
javadoc
wrapper - Gradle's wrapper
```

**Comment by jkschneider** [comment]
@mmoayyed Thanks for the report. I updated the doc to refer to the 0.22.0 version of the plugin rather than the old 0.10.0 version. At some point in the intervening time, we flipped the task name to `lintGradle` to disambiguate its short name with nebula.dependency-lock's `generateLock` task.
