### ISSUE TITLE
[v4.0.1] duplicate-dependency-class ignore no longer works

### ISSUE THREAD

**Issue by dotnal** [nebula-plugins/gradle-lint-plugin#43]
After the fix for #42, wrapping a block to ignore the rule `'duplicate-dependency-class'` doesn't seem to work any longer. This looks like it happens with both the standard way of declaring dependencies and the aliasing used in #42.

example: 
`gradleLint.ignore('duplicate-dependency-class') {
        testCompile "org.hamcrest:hamcrest-all:1.3"
    }`

now produces the console output 
`warning   duplicate-dependency-class         org.hamcrest:hamcrest-all:1.3 in configuration 'testCompile' has 45 classes duplicated by org.hamcrest:hamcrest-core:1.3`

**Comment by jkschneider** [comment]
@dotnal Thanks a bunch for the detailed report. This helps Netflixers too :)

**Comment by dotnal** [comment]
No worries, thanks heaps for the fix!
