### ISSUE TITLE
Lint plugin is not working with Dependency recommender

### ISSUE THREAD

**Issue by martin-linha** [nebula-plugins/gradle-lint-plugin#45]
Hi

first of all, thanks the effort with lint plugin. It's definitely a great and helpful plugin.

I am trying to use nebula.dependency-recommender in conjunction with nebula.lint. For nebula.lint plugin., the configuration is very straightforward

  apply plugin: 'nebula.lint'

    gradleLint.rules += 'all-dependency'

and for nebula.dependency-recommender

apply plugin: 'nebula.dependency-recommender'

dependencyRecommendations {
    propertiesFile file: rootProject.file('dependency-versions.properties')
}

When I do not specify version of a dependency in build script, like

compile junit:junit

 "unused-dependency" rule does not work. As soon as I add it like

compile junit:junit:3.4

it starts to work and I get a message that there is unused dependency. Note that lintGradle task is executed everytime.

Any ideas?

Thanks!
Martin

**Comment by jkschneider** [comment]
@martin-linha Thanks for the detailed example!
