### ISSUE TITLE
Not compatible with Gradle 3? 

### ISSUE THREAD

**Issue by mmoayyed** [nebula-plugins/gradle-lint-plugin#48]
```

* What went wrong:
A problem occurred evaluating root project 'cas-server'.
> Failed to apply plugin [id 'nebula.lint']
   > Could not create task of type 'FixGradleLintTask'.
```

Running with Gradle 3. The plugin in 2.14.x works just fine.

**Comment by mmoayyed** [comment]
Ignore. Using a very old version of plugin caused this issue.

**Comment by jkschneider** [comment]
Thanks @mmoayyed. You aren't entirely wrong. While 5.0.0 is Gradle 3.0 compatible, I've got some work to do to release a version that is backwards compatible with 2.x.

**Comment by mmoayyed** [comment]
Great. Thank you very much.
