### ISSUE TITLE
Provide a "skip" or "disable" option

### ISSUE THREAD

**Issue by krulls** [nebula-plugins/gradle-lint-plugin#51]
When using lint in a parent script that is inherited by other scripts / projects one sometimes wants to skip running the lint check.

I. e. while debugging script behaviour or something. When the lint plugin has been applied to a parent script, you cannot easily unapply it. So a configurable option like "skipLintCheck" or "disableLintCheck" would be a proper solution. At best this option is available for the command line to, providing something like "gradle clean build --lint.skipCheck" or "gradle clean build -Dlint.skip.check"

**Comment by jkschneider** [comment]
Does `./gradlew clean build -x lintGradle` suffice?

There is also a more targeted [ignore mechanism](https://github.com/nebula-plugins/gradle-lint-plugin/wiki/Ignoring-Violations).

**Comment by krulls** [comment]
"-x lintGradle" will help on the command line, thanks for the hint. I guess that the ignore mechanism will not stop the plugin from running at the end, inducing build time costs. Additionally I would have to embrace the whole buildscript with the ignore brackets, which is hard to read. 

I am used to the skip parameters from Maven and wonder that there is seldom implementation in Gradle plugins. It makes sense mostly in the construction of inheriting projects.

**Comment by jkschneider** [comment]
Unfortunately, Gradle does not allow plugins to provide `--lint.skipCheck` style command line options. The best you can do is `-Plint.skipCheck` (i.e. they only allow command line passing of properties), which isn't a whole lot different than `-x lintGradle`.

**Comment by krulls** [comment]
The "-P" switch is OK for me. I would suggest to use a common wording for the option. Such that you can use the same option name in the task configuration and the command line. I. e.:
- in the task: `lintGradle { skipGradleLint = true; }`, of course implement it for all tasks "fixGraldeLint" and "fixLintGradle" too
- for the commandLine: `gradle clean build -PskipGradleLint=true`

This way you prevent confusion and keep it simple. The implementation needs to check the task parameter and the project property accordingly. I would suggest to give the command line option higher priority, thus overwriting task parameter.

What do you think?

**Comment by jkschneider** [comment]
We recently introduced a property to the extension that allows you to turn off auto-running the lint tasks, so you can just specify it explicitly when you'd like. Works like this:

`gradleLint.alwaysRun = false`
