### ISSUE TITLE
Duplicate Warnings for Extended Configurations

### ISSUE THREAD

**Issue by sghill** [nebula-plugins/gradle-lint-plugin#53]
When one configuration extends from another and a direct dependency is undeclared in the super configuration, the same warning is shown twice:

```
warning   unused-dependency                  one or more classes in org.hamcrest:hamcrest-core:1.3 are required by your code directly
```

Manually fixing this by adding a dependency on hamcrest to the super configuration eliminates both warnings, but running `fixGradleLint` adds the dependency to both configurations.

Here is an [example project](https://github.com/sghill/gradle-lint-warnings-example) that reproduces this.

**Comment by jkschneider** [comment]
@sghill There might be something else in play. See the test committed in 39ca028, which shows only a single violation currently.

**Comment by sghill** [comment]
@jkschneider See updates to test in e70a93d. The test is actually still passing, but it's because of a formatting bug. The output looks like this:

```
:lintGradle

This project contains lint violations. A complete listing of the violations follows. 
Because none were serious, the build's overall status was unaffected.

one or more classes in org.hamcrest:hamcrest-core:1.3 are required by your code directly

one or more classes in org.hamcrest:hamcrest-core:1.3 are required by your code directly

warning   unused-dependency                  warning   unused-dependency                  ✖ build.gradle: 2 problems (0 errors, 2 warnings)
```

**Comment by jkschneider** [comment]
Thanks for the sample project @sghill. That made the problem really clear.
