### ISSUE TITLE
Support for excluding transitive project dependencies

### ISSUE THREAD

**Issue by Kinmarui** [nebula-plugins/gradle-lint-plugin#57]
Hi,

is there a way to tell gradle lint to ignore transitive dependencies from specified group?

I got error when running  unused-exclude-by-conf or unused-exclude-by-dep

```
 Could not resolve all dependencies for configuration 'detachedConfiguration113'.
  > Could not find [module_root]:[module]Commons:unspecified.
```

I use this project structure in my projects (microservice approach):
- [module]Commons
- [module]Client
- [module]Server

both Client and Server depends on Commons project

``` gradle
dependencies {
    compile project(':[module]Commons')
}
```

Problem arises when I add dependency on client in other module with excluding transitive dependency for Commons (I add it manually with proper version) 

``` gradle
compile("[module]Client:1.0.37"){
    exclude group: '[module_root]', module: '[module]commons' 
}
```

Or maybe I should reorganize my dependencies to not use project but versioned jar? This doesn't make sense to me since both subproject are stored in one repository.

**Comment by jkschneider** [comment]
Created a test for my understanding of the problem. If you still find there is an issue, please clarify the test. Thanks!
