### ISSUE TITLE
Lost color in terminal windows for at least gradle 2.13, 2.14.1

### ISSUE THREAD

**Issue by rspieldenner** [nebula-plugins/gradle-lint-plugin#63]
No color in terminal for lint messages in 2.13 and 2.14.1. Haven't tested with gradle 3.0, 3.1 yet.

**Comment by leonardschneider** [comment]
Same here. Reproduced on gradle 3.1.

**Comment by jkschneider** [comment]
Thanks @rspieldenner and @leonardschneider. Will be fixed in the 5.2.0 release coming today.
