### ISSUE TITLE
/org/eclipse/jgit/org.eclipse.jgit/4.4.0-SNAPSHOT/ is not found

### ISSUE THREAD

**Issue by TomDePauw** [nebula-plugins/gradle-lint-plugin#64]
hello, 

this is a double issue
-/org/eclipse/jgit/org.eclipse.jgit/4.4.0-SNAPSHOT/ is not on any repo?
-it only tries to download it when in gradle you put : 

> ```
>     maven {
>         url "https://plugins.gradle.org/m2/"
>     }
> ```

as the first repo

there is no problem when maven central  is the first repo configured

**Comment by BrianHegerty** [comment]
I see the 4.4.0 Snapshot in the project's build.gradle, but not in the jcenter repo's pom file. Shouldn't the dependency be moved off of a snapshot release?

**Comment by jkschneider** [comment]
Thanks for pointing this out @TomDePauw and @BrianHegerty
