### ISSUE TITLE
ignoreFailures in GradleLintReportTask is ignored

### ISSUE THREAD

**Issue by breskeby** [nebula-plugins/gradle-lint-plugin#66]
there is currently no way to let the GradleLintReportTask fail if violations found. I'd like to have the report generated but fail the task. otherwise I have no way to indicate violations have been found apart from scanning the log output.

**Comment by jkschneider** [comment]
I'll go one step further and allow you to differentiate between rules that result in failures and those that don't, i.e.:

```
gradleLint {
  rules  = ['dependency-parentheses']
  criticalRules = ['unused-dependency'] // <-- this will fail the build in the event of a violation
}

Violations of critical rules will fail the report task, the regular `lintGradle` task, and the `fixGradleLint` task in the event that the violation was not completely remediated by the rule.
