### ISSUE TITLE
Allow configuration of lintGradle task invocation behaviour 

### ISSUE THREAD

**Issue by breskeby** [nebula-plugins/gradle-lint-plugin#68]
sorry for the maybe confusing title but I'm not sure how to phrase it better. We want to use the lint plugin in our project but we want to specify explicitly when to run the lint task. E.g. we only want it to run with our sanityCheck task. 

The current default behaviour of always running lintGradle at the end of the build is kind of to much as it adds significant build time to all of our builds. (e.g. resulting in a 2s build to run now 15s with lintPlugin applied. We worked around this by only applying the lint plugin when sanityCheck is explicitly triggered but that is a workaround I'd like to get rid of. 

What about having a flag in the lint extension to disable / enable auto applying the lintGradle task?

**Comment by jkschneider** [comment]
Sounds reasonable @breskeby. Added an `alwaysRun` property to the extension object, that when false, will not automatically run `lintGradle`.
