### ISSUE TITLE
Duplicate Dependency Class Miss

### ISSUE THREAD

**Issue by sghill** [nebula-plugins/gradle-lint-plugin#73]
The duplicate dependency class rule sometimes misses detecting duplicates, notably with `guava` and `guava-jdk5`. See this [example build.gradle](https://github.com/sghill/dup-classes-issue/blob/master/build.gradle). As these jars have a lot of overlap, we'd expect the rule to issue warnings.

**Comment by jkschneider** [comment]
Dependency rules do not eagerly resolve configurations, since this could have adverse performance consequences. Running `./gradlew assemble` causes the violation to be reported.

**Comment by jhspaybar** [comment]
If this is really the root cause, why is assemble not a dependency of the lint?

**Comment by jkschneider** [comment]
@jhspaybar I'm open to reconsidering this. Right now, lintGradle adds itself as a task to run after pretty much every other task (minus 'core' tasks like dependencies, tasks, etc.). So adding assemble would contravene the user's intention.

One possibility I discussed with @sghill was to eagerly resolve configurations (and therefore run dependency-based rules) if you explicitly ask lintGradle to run, but not when it adds itself to the task graph. WDYT?

**Comment by jhspaybar** [comment]
I think that if I run ./gradlew lint it should exactly that and lint my project without me needing to know the implementation details.
