### ISSUE TITLE
Run enabled conditional rules when lintGradle is specified explicitly

### ISSUE THREAD

**Issue by DanielThomas** [nebula-plugins/gradle-lint-plugin#74]
A common source of confusion for dependency related rules, is that an implicit run will only look at configurations resolved, and not all configurations.

Instead, when `lintGradle` is specified we should run all enabled, conditional rules, such as dependency rules against _all_ configurations.

Think it'd be a good idea to add a `fixAllGradleLint` as a way of explicitly fixing all violations, rather than depending on the tasks run (as documented in #70).

**Comment by DanielThomas** [comment]
Another option is to make the implicit task `lintGradleFast` or whatever, and `lintGradle` always run  everything. That'd avoid the tricky detection of whether the task was explicitly requested.

**Comment by DanielThomas** [comment]
@jhspaybar any additional comments?

**Comment by jhspaybar** [comment]
I'm mostly concerned with the UX and want the most likely command I'll run to check everything. Maybe lintGradle runs it all and lintNoResolutionGradle be the fast one?  Then lG works and the autocomplete stuff picks the slow one by default.
