### ISSUE TITLE
 Bad <init> method call from inside of a branch

### ISSUE THREAD

**Issue by ravendra-gupta** [nebula-plugins/gradle-lint-plugin#76]
Env:  
Gradle: 3.0
JDK: 1.8_11
plugin: gradle-lint-plugin 6.1.4

error:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lintGradle'.
> Bad <init> method call from inside of a branch
Exception Details:
  Location:
    com/netflix/nebula/lint/VersionNeutralTextOutput.<init>()V @75: invokespecial
  Reason:
    Error exists in the bytecode
  Bytecode:
    0000000: b800 1c4c 04bd 0004 5903 0112 04b8 005d
    0000010: 5359 10ff 1202 b800 612a 5fab 0000 004c
    0000020: 0000 0003 9bec 5417 0000 0021 0000 9b75
    0000030: 0000 0036 5d52 7811 0000 003f 5f5a 5903
    0000040: 3212 3cb8 0067 c000 3c5f 57b7 0069 a700
    0000050: 235f 5a57 b700 6aa7 001a 5f5a 5903 325f
    0000060: 57b7 006c a700 0dbb 0030 5912 6eb7 0071
    0000070: bf57 b1                                
  Stackmap Table:
    full_frame(@60,{UninitializedThis,Object[#62]},{Object[#99],UninitializedThis})
    full_frame(@81,{UninitializedThis,Object[#62]},{Object[#99],UninitializedThis})
    full_frame(@90,{UninitializedThis,Object[#62]},{Object[#99],UninitializedThis})
    full_frame(@103,{UninitializedThis,Object[#62]},{Object[#99],UninitializedThis})
    full_frame(@113,{Object[#2],Object[#62]},{Object[#99]})

**Comment by jkschneider** [comment]
@ravendra-gupta This was a flaw in JDK 1.8_11 itself that affected lots of Groovy code. Upgrade to a later version (latest I believe is 1.8_121) and you will be good to go!

**Comment by ravendra-gupta** [comment]
Thanks, I upgarded jdk and it is working now as per expections
