### ISSUE TITLE
Don't run automatic lintGradle when build fails

### ISSUE THREAD

**Issue by DanielThomas** [nebula-plugins/gradle-lint-plugin#77]
Currently, a build failure can be obscured (and you're left waiting) on when a build fails. Ideally, the automatic lint shouldn't run on failure.

**Comment by drjasonharrison** [comment]
After `apply plugin: 'nebula.lint'`
add
`autoLintGradle.dependsOn subprojects*.build`

**Comment by DanielThomas** [comment]
@drjasonharrison thanks - I'm actually @ Netflix, this was just to remind me to implement an `onlyIf` that checks the task graph for failures (going out in the next release).
