### ISSUE TITLE
autoLintGradle task ignores gradleLint.alwaysRun

### ISSUE THREAD

**Issue by yoavain-sundaysky** [nebula-plugins/gradle-lint-plugin#79]
This is a regression.
It worked on 6.1.4 but not on 6.2.0/6.2.1

**Comment by jkschneider** [comment]
@yoavain-sundaysky Thanks for the quick report! Ensured that this is covered by a test now for the future. The fix will be available in 6.2.2 in a few minutes.

**Comment by yoavain-sundaysky** [comment]
thanks! 
fix approved ;)
