### ISSUE TITLE
autoLintGradle fails in Gradle 3.3

### ISSUE THREAD

**Issue by CSBaum** [nebula-plugins/gradle-lint-plugin#83]
When the autoLintGradle task is run I get the following error:

`Error from [com.netflix.nebula.lint.rule.GradleLintRule$1] processing source file [null]`

With the following explanation on what went wrong:
```
* What went wrong:
Execution failed for task ':autoLintGradle'.
> class com.netflix.nebula.lint.rule.dependency.DependencyClassVisitor has interface org.objectweb.asm.ClassVisitor as super class
```
I have tried this using gradle 3.2 and 3.3.  If you need anything else from me please let me know.

Sean

**Comment by DanielThomas** [comment]
@CSBaum could we start with the output of the `buildEnvironment` task. Chances are this is a buildscript classpath issue.

**Comment by jkschneider** [comment]
I believe the key to this fix is to exclude old versions of ASM from your buildscript classpath, e.g.:

```
buildscript.configurations.classpath {
   exclude group: 'asm', module: 'asm'
   exclude group: 'asm', module: 'asm-all'
}
```
