### ISSUE TITLE
Ability to Exclude Transitive Rules

### ISSUE THREAD

**Issue by sghill** [nebula-plugins/gradle-lint-plugin#86]
It'd be great if we could exclude transitive rules from `gradleLint.rules`.

For example, if `gradleLint.rules` is `['a', 'b']` by default, I can say
`gradleLint.rules -= 'b'` and only have 'a' in the set. But if I defined a rule 'c' that includes 'a' and 'b', I can no longer exclude 'b' because 'c' is the only thing present in the collection.

**Comment by jkschneider** [comment]
The new wiki page for this is [here](https://github.com/nebula-plugins/gradle-lint-plugin/wiki/Excluding-Rules).
