### ISSUE TITLE
autoLintGradle produces miss-leading output if compile fails

### ISSUE THREAD

**Issue by gregallen** [nebula-plugins/gradle-lint-plugin#93]
Seen with Gradle 2.12

workaround is to add

    autoLintGradle.onlyIf { !tasks*.state.failure.any() }

**Comment by jkschneider** [comment]
@gregallen Out of curiosity, what was misleading about the output?

**Comment by gregallen** [comment]
Lots of extra unused-dependency  warnings

I'm using the all-dependency group rule

**Comment by jkschneider** [comment]
Makes sense, thanks.

**Comment by gregallen** [comment]
Perhaps makes more sense to add check on its dependencies (classes?) for success, or to add it to the check task instead

**Comment by DanielThomas** [comment]
@gregallen believe the `autoLintAfterFailure` feature I added should address your concern?

https://github.com/nebula-plugins/gradle-lint-plugin/wiki/Using-Lint#disabling-automatic-lint

If not, let me know with some more details and I'll reopen this issue.
