### ISSUE TITLE
Release v7.0.0 created regression

### ISSUE THREAD

**Issue by remy-tiitre** [nebula-plugins/gradle-lint-plugin#94]
When you have duplicated classes in your classpath (For us its unfortunate case that we are using log4j and log4j-extras and those have duplicated classes) then DuplicateDependencyClassRule will crash with "Caused by: java.lang.NullPointerException: Cannot get property 'state' on null object" error. I have narrowed it down to DuplicateDependencyClassRule.groovy modification at lines 22-24 and the probable cause might be that project.configurations.findByName(conf) does not return proper object. Don't have more time to investigate it right now.

**Comment by jkschneider** [comment]
@remy-tiitre I'd be interested in writing a better test for this for the future. What conf name was it that we failed to find in the gradle configuration container that later resulted in an NPE?

**Comment by remy-tiitre** [comment]
I'm not sure. I think there is no other option than to modify the lint plugin to output the conf name that it fails on. Configurations that failing projects had in common: archives, checkstyle, compile, compileClasspath, compileOnly, default, findbugs, findbugsPlugins, providedCompile, providedRuntime, resolutionRules, runtime, testCompile, testCompileClasspath, testCompileOnly, testRuntime. So mostly classical Java configurations.
